// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozeprmnncieoqpntvvpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96ZXBybW5uY2llb3FwbnR2dnB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NTExMDgsImV4cCI6MjA1ODIyNzEwOH0.RkAms18Sl4nOlmUoBf6VzihomxWj6fLNPPNh8bn18_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);